### ISSUE TITLE
"Input is null" log spam

### ISSUE THREAD

**Issue by JebsSY** [jrossignol/ContractConfigurator#614]
CC is a litte bit spamming the log with Input is null....

I wonder, if the title in [this line](https://github.com/jrossignol/ContractConfigurator/blob/9a33f0fde9c8e0ddffecfeddca91e42995288994/source/ContractConfigurator/Parameter/VesselParameter/Docking.cs#L77) is without reference and causing this?

`[ERR 01:53:09.832] Input is null for field 'title' in config node 'PARAM'
   at System.Environment.get_StackTrace()
   at ConfigNode.AddValue(System.String name, System.String value)
   at ContractConfigurator.Parameters.Docking.OnParameterSave(.ConfigNode node)
   at ContractConfigurator.Parameters.ContractConfiguratorParameter.OnSave(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.Contract.Save(.ConfigNode node)
   at ContractConfigurator.ContractPreLoader.OnSave(.ConfigNode node)
   at ScenarioModule.Save(.ConfigNode node)
   at ProtoScenarioModule..ctor(.ScenarioModule module)
   at ScenarioRunner.UpdateModules()
   at ScenarioRunner.GetUpdatedProtoModules()
   at Game.Updated()
   at GamePersistence.SaveGame(System.String saveFileName, System.String saveFolder, SaveMode saveMode)
   at MCSceneSpawner.OnMCDespawn()
   at EventVoid.Fire()
   at MCDespawner.BtnExit()
   at UnityEngine.Events.InvokableCall.Invoke(System.Object[] args)
   at UnityEngine.Events.InvokableCallList.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEventBase.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEvent.Invoke()
   at UnityEngine.UI.Button.Press()
   at UnityEngine.UI.Button.OnPointerClick(UnityEngine.EventSystems.PointerEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress(UnityEngine.EventSystems.MouseButtonEventData data)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent(Int32 id)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent()
   at UnityEngine.EventSystems.StandaloneInputModule.Process()
   at UnityEngine.EventSystems.EventSystem.Update()`

**Comment by jrossignol** [comment]
These are typically not an issue, but I'll double check (and get it to stop
the spam).  It used to not say anything other than "input is null", so
these usually weren't worth tracking down.  Now there's enough info to make
it fairly simple.

**Comment by jrossignol** [comment]
Fixed by #619
