### ISSUE TITLE
NREs when title is empty

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#619]
Posting here so it won't get lost, I copied it from http://forum.kerbalspaceprogram.com/index.php?/topic/91625-12x-contract-configurator-v1222-2016-12-16/&do=findComment&comment=2915064

I wanted to ask, if these CC exceptions are harmless. Do I get them cause I removed a part mod? (Complete log aviable).
I have top say this is a highly modded install but I keep a close eye on the errors and it runs crash free atm.
Cause they are from a stream I can in theory find and show the video on the time where the errors occur, if that helps debugging.

I had a NRE caused on "Tito Kerman" with Kerbalstats from the "Kick of Space Tourism (Tourism Plus)" mission, which I have reported here in detail. Maybe it is related?
 

  Hide contents
[LOG 01:51:50.790] [Progress Tracking Parser] Progress Nodes Loaded...
[ERR 01:51:52.867] Input is null for field 'title' in config node 'PARAM'
   at System.Environment.get_StackTrace()
   at ConfigNode.AddValue(System.String name, System.String value)
   at ContractConfigurator.Parameters.Docking.OnParameterSave(.ConfigNode node)
   at ContractConfigurator.Parameters.ContractConfiguratorParameter.OnSave(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.Contract.Save(.ConfigNode node)
   at SSTUTools.RescueContractPartSelector.OnContractOffered(Contracts.Contract contract)
   at EventData`1[[Contracts.Contract, Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Fire(Contracts.Contract data)
   at Contracts.Contract.SetState(State newState)
   at ContractConfigurator.ConfiguredContract.set_ContractState(State value)
   at ContractConfigurator.ContractPreLoader+<GenerateContract>d__33.MoveNext()
   at ContractConfigurator.ContractPreLoader+<ContractEnumerator>d__32.MoveNext()
   at ContractConfigurator.ContractPreLoader.Update()

[LOG 01:52:20.358] [1/9/2017 1:52:20 AM] [TimeControl(2.50): ]: <Info> (TCGUI.onShowUI) - Unhiding GUI for Settings Lock
[LOG 01:52:20.359] [UIMasterController]: ShowUI
[LOG 01:52:20.360] Game Paused!
[LOG 01:52:20.368] QuickGoTo(QStockToolbar)[1.31]: OnHide
[LOG 01:52:51.423] Awarding 45000 funds to player for contract advance
[LOG 01:53:09.805] [1/9/2017 1:53:09 AM] [TimeControl(2.50): ]: <Info> (TCGUI.onShowUI) - Unhiding GUI for Settings Lock
[LOG 01:53:09.807] [UIMasterController]: ShowUI
[LOG 01:53:09.809] Game Unpaused!
[LOG 01:53:09.810] Flight State Captured
[LOG 01:53:09.817] Saving Achievements Tree...
[LOG 01:53:09.819] Saving Achievements Tree...
[LOG 01:53:09.821] Saving Achievements Tree...
[LOG 01:53:09.823] Saving Achievements Tree...
[LOG 01:53:09.825] Saving Achievements Tree...
[ERR 01:53:09.832] Input is null for field 'title' in config node 'PARAM'
   at System.Environment.get_StackTrace()
   at ConfigNode.AddValue(System.String name, System.String value)
   at ContractConfigurator.Parameters.Docking.OnParameterSave(.ConfigNode node)
   at ContractConfigurator.Parameters.ContractConfiguratorParameter.OnSave(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.Contract.Save(.ConfigNode node)
   at ContractConfigurator.ContractPreLoader.OnSave(.ConfigNode node)
   at ScenarioModule.Save(.ConfigNode node)
   at ProtoScenarioModule..ctor(.ScenarioModule module)
   at ScenarioRunner.UpdateModules()
   at ScenarioRunner.GetUpdatedProtoModules()
   at Game.Updated()
   at GamePersistence.SaveGame(System.String saveFileName, System.String saveFolder, SaveMode saveMode)
   at MCSceneSpawner.OnMCDespawn()
   at EventVoid.Fire()
   at MCDespawner.BtnExit()
   at UnityEngine.Events.InvokableCall.Invoke(System.Object[] args)
   at UnityEngine.Events.InvokableCallList.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEventBase.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEvent.Invoke()
   at UnityEngine.UI.Button.Press()
   at UnityEngine.UI.Button.OnPointerClick(UnityEngine.EventSystems.PointerEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress(UnityEngine.EventSystems.MouseButtonEventData data)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent(Int32 id)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent()
   at UnityEngine.EventSystems.StandaloneInputModule.Process()
   at UnityEngine.EventSystems.EventSystem.Update()

[LOG 01:53:09.838] QuickStart(QPersistent)[2.11]: OnSave 0d8cd759-8e9e-4570-bdf8-f20257849118
[LOG 01:53:09.840] DeepFreeze Scenario OnSave completed.
[LOG 01:53:09.920] [MessageSystem] Save Messages
[LOG 01:53:09.932] [KerbalStats] saving ext for Jebediah Kerman
[LOG 01:53:09.934]     from kerbals
[LOG 01:53:09.935] [KerbalStats] saving ext for Bill Kerman
[LOG 01:53:09.937]     from kerbals
[LOG 01:53:09.939] [KerbalStats] saving ext for Bob Kerman
[LOG 01:53:09.941]     from kerbals
[LOG 01:53:09.943] [KerbalStats] saving ext for Valentina Kerman
[LOG 01:53:09.945]     from kerbals
[LOG 01:53:09.946] [KerbalStats] saving ext for Jerdock Kerman
[LOG 01:53:09.948]     from kerbals
[LOG 01:53:09.950] [KerbalStats] saving ext for Gertrix Kerman
[LOG 01:53:09.952]     from kerbals
[LOG 01:53:09.953] [KerbalStats] saving ext for Elicine Kerman
[LOG 01:53:09.955]     from kerbals
[LOG 01:53:09.957] [KerbalStats] saving ext for Edmy Kerman
[LOG 01:53:09.959]     from kerbals
[LOG 01:53:09.962] [KerbalStats] saving ext for Nedgard Kerman
[LOG 01:53:09.963]     from kerbals
[LOG 01:53:09.965] [KerbalStats] saving ext for Ladine Kerman
[LOG 01:53:09.967]     from kerbals
[LOG 01:53:09.969] [KerbalStats] saving ext for Rosy Kerman
[LOG 01:53:09.971]     from kerbals
[LOG 01:53:09.972] [KerbalStats] saving ext for Maltrey Kerman
[LOG 01:53:09.974]     from kerbals
[LOG 01:53:09.976] [KerbalStats] saving ext for Sutrix Kerman
[LOG 01:53:09.978]     from kerbals
[LOG 01:53:09.980] [KerbalStats] saving ext for Tomler Kerman
[LOG 01:53:09.982]     from kerbals
[LOG 01:53:09.983] [KerbalStats] saving ext for Billorf Kerman
[LOG 01:53:09.985]     from kerbals
[LOG 01:53:09.987] [KerbalStats] saving ext for Dilin Kerman
[LOG 01:53:09.989]     from kerbals
[LOG 01:53:10.004] Game State Saved to saves/122-Twitch/persistent
[LOG 01:53:10.008] [UIMasterController] RemoveCanvas:MissionControl
[LOG 01:53:20.700] [ContractSystem]: Contract Conduct observational surveys of the Mun. is no longer being offered by REPOSoftTech
[LOG 01:53:45.990] [1/9/2017 1:53:45 AM] [TimeControl(2.50): ]: <Info> (TCGUI.onShowUI) - Unhiding GUI for Settings Lock
[LOG 01:53:45.992] [UIMasterController]: ShowUI
[LOG 01:53:45.993] Game Paused!
[LOG 01:53:52.807] Flight State Captured
[LOG 01:53:52.814] Saving Achievements Tree...
[LOG 01:53:52.816] Saving Achievements Tree...
[LOG 01:53:52.818] Saving Achievements Tree...
[LOG 01:53:52.819] Saving Achievements Tree...
[LOG 01:53:52.822] Saving Achievements Tree...
[ERR 01:53:52.828] Input is null for field 'title' in config node 'PARAM'
   at System.Environment.get_StackTrace()
   at ConfigNode.AddValue(System.String name, System.String value)
   at ContractConfigurator.Parameters.Docking.OnParameterSave(.ConfigNode node)
   at ContractConfigurator.Parameters.ContractConfiguratorParameter.OnSave(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.ContractParameter.Save(.ConfigNode node)
   at Contracts.Contract.Save(.ConfigNode node)
   at ContractConfigurator.ContractPreLoader.OnSave(.ConfigNode node)
   at ScenarioModule.Save(.ConfigNode node)
   at ProtoScenarioModule..ctor(.ScenarioModule module)
   at ScenarioRunner.UpdateModules()
   at ScenarioRunner.GetUpdatedProtoModules()
   at Game.Updated()
   at KSCPauseMenu.doSave(System.String filename)
   at KSCPauseMenu.<ConfirmDialog>m__830()
   at DialogGUIButton.OptionSelected()
   at DialogGUIButton.<Create>m__6F1()
   at UnityEngine.Events.InvokableCall.Invoke(System.Object[] args)
   at UnityEngine.Events.InvokableCallList.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEventBase.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEvent.Invoke()
   at UnityEngine.UI.Button.Press()
   at UnityEngine.UI.Button.OnPointerClick(UnityEngine.EventSystems.PointerEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress(UnityEngine.EventSystems.MouseButtonEventData data)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent(Int32 id)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent()
   at UnityEngine.EventSystems.StandaloneInputModule.Process()
   at UnityEngine.EventSystems.EventSystem.Update()

[LOG 01:53:52.834] QuickStart(QPersistent)[2.11]: OnSave 0d8cd759-8e9e-4570-bdf8-f20257849118
[LOG 01:53:52.836] DeepFreeze Scenario OnSave completed.
[LOG 01:53:52.911] [MessageSystem] Save Messages
[LOG 01:53:52.922] [KerbalStats] saving ext for Jebediah Kerman
[LOG 01:53:52.924]     from kerbals

There are some empty TITLE= *nothing* in my save game, but I assume this is normal?

  Hide contents
                PARAM
                {
                    name = ReachDestination
                    state = Incomplete
                    disableOnStateChange = False
                    values = 0,0,0,0,0
                    dest = 1
                    title = 
                }

 

EDIT: Seems like replacing all "title = *newline*" by "title = temptitle*newline*" in the CC section of my save game fixed the NRE. However, I assume it will generate more contracts with empty params titles.

Is this by design? If yes, could these exceptions maybe be catched to not clutter the log? :)

EDIT2: One thing that could mess with contracts maybe, that I have installed is the rescue pod fix. (https://github.com/shadowmage45/KSPRescuePodFix)

EDIT3: Might this line (https://github.com/jrossignol/ContractConfigurator/blob/9a33f0fde9c8e0ddffecfeddca91e42995288994/source/ContractConfigurator/Parameter/VesselParameter/Docking.cs#L77) (missing title?) be the cause?

**Comment by jrossignol** [comment]
Funny enough, the Docking title lines in OnSave/OnLoad are completely redundant.  Although annoying, the "Input is null" error messages are completely harmless and should really be warnings (Bill added the stack trace in KSP 1.2, which makes them seem even scarier).

Anyway, fixed for next release.
